default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  user: Austris

development:
  <<: *default
  database: CHEVRON_development

test:
  <<: *default
  database: CHEVRON_test

production:
  <<: *default
  database: CHEVRON_production
  username: CHEVRON
  password: <%= ENV['CHEVRON_DATABASE_PASSWORD'] %>
