default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  user: Austris

development:
  <<: *default
  database: Interface_development

test:
  <<: *default
  database: Interface_test

production:
  <<: *default
  database: Interface_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
